### PR TITLE
Fixes JDK-8144165 (backport JDK 8)

### PR DESCRIPTION
**Pull request by FibreFoX**
When bundling your application with the JNLP-bundler, all jar-files are using RelativeFileSets, which contain os-spezific separators. The problem is, that on windows there are backslashes, which are written into the generated JNLP-files, and having backslashes inside href-attributes is not valid for webservers, which do not translate backslashes into normal slashes.

The original bug-ticket wasn't that precise, thats the reason it got closed as incomplete.

http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8144165
https://bugs.openjdk.java.net/browse/JDK-8144165

### CODE REVIEW

**Comment by FibreFoX** [comment]
This got already workedaround within [javafx-gradle-plugin](https://github.com/FibreFoX/javafx-gradle-plugin/blob/8.4.1/src/main/java/de/dynamicfiles/projects/gradle/plugins/javafx/tasks/JfxNativeTask.java#L478) and [javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/javafx-maven-plugin-8.4.0/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L768)

**Comment by mkarg** [comment]
This is only a read-only mirror, so pull requests cannot be processed. Instead please describe your proposal as an issue. Thanks.

**Comment by FibreFoX** [comment]
@mkarg there is no read-only flag here on github, please describe where to create pull-requests ... I think we need to talk about this on the mailinglist ...

**Comment by mkarg** [comment]
It is impossible to create pull-requests against OpenJFX _anywhere_ as Oracle's original SCM is not git. Oracle expects people to send in patch files on their mailing list. So unless somebody at TeamFX is willing to create patch files from pull requests, we cannot accept pull requests.

**Pull request closed without merging**
